questions:
  - name: 
      prompt: What is your name?
      type: string
  - faveThings:
      prompt: What are a few of your favourite things?
      type: stringArray
templates:
  - helloWorld
  - withSubFolder
headline: This workflow is your introduction to credo! Click the rocket!