parameters:
  name:
    type: string
  shouldFetchOnLoad:
    type: boolean
  fetchedResourceName:
    type: string
  tests:
    type: stringArray
  styleRules:
    type: stringArray
    
tags:
  - react
  - welcome
  - frontend
  - credo