headline: How to write data layer access for a gql resource
questions:
  - name:
      type: string
      prompt: What is the name of the resource?
  - fields:
      type: stringArray
      prompt: What fields does this resource have? [fieldName:fieldType]
      subtext: You can capitalize fieldType and it will treat the type as non-inferrable
  - resolver:
      type: boolean
      prompt: Does this resource need a resolver?
  - loader:
      type: boolean
      dependentKey: resolver
      prompt: Do you want to supply the resolver with a DataLoader?
      subtext: The DataLoader abstraction batches db queries.
templates:
  - prismaGqlResolver
tags:
  - graphql
