questions:
  - name:
      type: string
      prompt: To get us started, what is your name? (it doesn't need to be your real name, just something we can call you for the duration of this welcome)
  - isDeveloper:
      prompt: Awesome, now it's probably fair to say that if you're here it's because you're a developer of some kind, is that right?
      type: boolean
templates:
  - welcome