headline: Get started with Credo
questions:
  - name:
      type: string
      prompt: To get us started, what is your name?
      subtext:  it doesn't need to be your real name, just something we can call you for the duration of this welcome
  - ready:
      type: boolean
      prompt: Ready to get going?
  - learnMore:
      prompt: Would you like to learn more?
      type: boolean
templates:
  - welcome
