headline: Get started with Credo
questions:
  - name:
      type: string
      prompt: To get us started, what is your name?
      subtext:  it doesn't need to be your real name, just something we can call you for the duration of this welcome
  - ready:
      type: boolean
      prompt: Ready to get going?
      dependentKey: name
  - fibType:
      type: enum
      prompt: "Let's show how snippets can be rendered conditionally, pick a complexity:"
      dependentKey: ready
      enumMembers:
        - O(n)
        - Recursive (and exponential)
        - Recursive (with memoization (linear))
  - readyForSubDirs:
      type: boolean
      prompt: Ready to learn about subdirectories and templates?
      dependentKey: fibType
  - fetchesResource:
      type: boolean
      prompt: Does the component make a get request when it first renders?
  - fetchedResourcePath:
      type: string
      dependentKey: fetchesResource
      prompt: What is the url for the fetched resource?
      subtext: it'll probably look something like '/api/whatever'
templates:
  - welcome
